- name: Implementaci贸nes en Windows 
  hosts: all
  collections:
    - chocolatey.chocolatey
  tasks:
    - name: Hello Message
      win_ping:
    - name: Instalar paqueteria en el modulo de virtual
      win_chocolatey:
        name:
        - vscode
       # - git
       # - chromium
       # - dropbox
       # - docker-desktop
        state: latest
    - name: Actualizaci贸n de Sanidad para controladores y parches de seguridad 
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: installed
      register: update_result
    - name: Reiniciar si es necesario
      win_reboot:
      when: update_result.reboot_required
   # - name: Toma de inventarios de componentes para entregables a inventario
   #  win_command: systeminfo
   #  register: system_info
    - name: Mostrar ventana emergente de actualizaci贸n
      win_shell: |
        Add-Type -AssemblyName PresentationFramework
        [System.Windows.MessageBox]::Show('El sistema ha sido actualizado y configurado por el administrador, puede continuar trabajando', 'Actualizaci贸n Completa')
      when: update_result.changed
      ignore_errors: yes
