- name: Crear VM con ISO en vCenter
  hosts: VMWare
  collections: 
         - vmware.vcenter_extension
  gather_facts: False
  tasks:
     - name: Crear VM en Vcenter host
       vmware_guest:
          datacenter: "{{ vcenter_datacentername}}"
          hostname: "{{ vcenter_hostname }}"
          username: "{{ vcenter_username }}"
          password: "{{ vcenter_password }}"
          validate_certs: no
          folder: /
          name: test_vm_prueba
          state: powered-off
          guest_id: rhel8_64Guest
          esxi_hostname: "{{ esxi_hostname }}"
          disk:
             - size_gb: 15
               type: thin
               datastore: "{{ vcenter_datastore }}"
          cdrom:
             - type: iso
               iso_path: "[datastore1 (1)] rhel-8.5-x86_64-boot.iso"
               controller_number: 1  # Número de controlador
               unit_number: 0
               state: present
          hardware:
             memory_mb: 8192
             num_cpus: 4
          wait_for_ip_address: no
       delegate_to: localhost
