- name: Implementaciones en Windows 
  hosts: all
  collections:
    - chocolatey.chocolatey
    - ansible.windows
  tasks:
    - name: Hello Message
      win_ping:

    - name: Desactivar Windows Defender Antivirus temporalmente
      win_shell: Set-MpPreference -DisableRealtimeMonitoring $true
      become: yes
      become_method: runas
      ignore_errors: yes
      
    - name: Actualizar todos los paquetes de Windows
      win_updates:
        category_names: 
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        state: installed
        register: update_result
