- name: Implementaciones en Windows 
  hosts: all
  collections:
    - chocolatey.chocolatey
    - ansible.windows
  tasks:
    - name: Hello Message
      win_ping:

    - name: Desactivar Windows Defender Antivirus temporalmente
      win_shell: Set-MpPreference -DisableRealtimeMonitoring $true
      become: yes
      become_method: runas
      ignore_errors: yes
      
    - name: Actualizar todos los paquetes de Windows
      win_updates:
        category_names: 
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
        state: installed
        register: update_result

    - name: Reboot the machine if required and wait for it to come back
      ansible.windows.win_reboot:
        when: update_result.reboot_required

    - name: Reactivar Windows Defender Antivirus después de las actualizaciones
      win_shell: Set-MpPreference -DisableRealtimeMonitoring $false
      become: yes
      become_method: runas
      ignore_errors: yes
      when: update_result.reboot_required
